package Modelo;

public enum Eventos {
    JUGADOR_AGREGADO,
    COMENZAR_JUEGO,
    DADOS_CON_PUNTOS,
    DADOS_SIN_PUNTOS,
    ACTUALIZACION_TURNO,
    DADOS_APARTADOS,
    PUNTAJE_ACTUALIZADO,
    DADOS_LANZADOS,
    ACTUALIZAR_DADOS_LANZADOS,
    ESCALERA_OBTENIDA
}
